= RShiny Application in R

RShiny is a package from RStudio to build interactive web applications in __R__. With interactive here means that one can change the input values on the web page and can view the output generated with that input on the web page at the same instance. There is no need to reload the web page for changes to appear. This package completely eliminates the need to use HTML,CSS,Javascript for building a web application.

ShinyApp consists of two components:

- ui.r file
- server.r file

#### ui.r file
This file contains the user interface object. You can define the 
inputs for the web application in this file. Following are the basic components for this file:

```R
library(RShiny)
shinyUI(fluidpage())
```

In the above code, the first line loads the RShiny library. The `ShinyUI()` function builds the UI object for the web application. In RShiny, you can have function inside a function. Inside `ShinyUI()` function, you can have various functions for laying out the user interface. 

I am also using `fluidpage()` function as a parameter for `ShinyUI()` to create a fluid layout which we will see in the below sections.

If you want to see other functions, feel free to use the below link : https://shiny.rstudio.com/reference/shiny/1.0.5/


```R
# filename: ui.r

library(RShiny)
shinyUI(fluidPage(

  titlePanel("Hello, Welcome to a Rshiny Web Application!!"),
  
  # sliderInput
  # builds a slider in the sidebar
  # @param "obs" input variable name
  # @param "Number of observations:" Slider title
  # @param min = 1 min slider value
  # @param max = 100 max slider value
  # @param value = 500 By default selected value
  sidebarLayout(
    sidebarPanel(
      sliderInput("obs", "Number of observations:",  
                  min = 1, max = 1000, value = 500) 
    ),

    mainPanel(
      plotOutput("distPlot") 
      # to print the plot's output where 
      # output variable is distPlot.
    )
  )
))
```

Inside `fluidPage()` function, you can see three components:

- titlePanel
- sidebarLayout
- mainPanel

1) `titlePanel` includes the title of the webpage.

2) `sidebarPanel` includes the components on the sidebar. By default, sidebar is on the left-hand side, but you can move it towards the right with the help of the following code:

```R
sidebarLayout(position = "right",            
  sidebarPanel(
  ),
  mainPanel(
  )
)
```

3) `mainPanel` includes the center section of the webpage where we can print/display our output. 

#### server.r file

`server.r` is the file that is responsible for the computational part of the RShiny App.

```R
# filename: server.r

library(RShiny)
ShinyServer(function(input,output) {

})
```

The above code contains the basic component for the `server.r` file. You can define the output to be generated inside this `ShinyServer()` function. I am going to plot a histogram for randomly generated numbers using `rnorm()` function.

```R
library(RShiny)
ShinyServer(function(input,output) {
  output$distPlot <- renderPlot({
    dist <- rnorm(input$obs)
    hist(dist)
  })
})
```

`render` is a family of functions which are reactive in nature. This means that the output changes with the change in input. In order to plot a graph, we will use the function `renderPlot()`. 

You can find the other `render` functions using the following link: https://shiny.rstudio.com/reference/shiny/1.0.5/ 

So prior to RShiny version 0.10, there was a need to call `ShinyUI()` and `ShinyServer()` functions in `ui.r` and `server.r` files respectively. But from RShiny version 0.10, there is no more need to call these functions seperately in two different files anymore. We can use a single file to call a single function, `ShinyApp()` inside `App.R` file.


```R
# filename: App.R

server <- function(input, output) {
  
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(),
    mainPanel()
    )
)
shinyApp(ui = ui, server = server)
```

server and ui will function in the above code will be the same as described in the start of the blog. ShinyApp() here knits the ui and server functions together.

The output of the above ui.r and server.r files will generate the following output. 
##have to include a SS
You can visit the following link to perform the changes on your own.

References:

https://shiny.rstudio.com/reference/shiny/1.0.5/
https://shiny.rstudio.com/articles/app-formats.html
